# Generated by Django 3.1.2 on 2020-10-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodremainingtimes',
            old_name='Location_Id_1',
            new_name='Location_Id',
        ),
        migrations.RemoveField(
            model_name='foodremainingtimes',
            name='Location_Id_2',
        ),
        migrations.RemoveField(
            model_name='foodremainingtimes',
            name='Location_Id_3',
        ),
        migrations.RemoveField(
            model_name='foodremainingtimes',
            name='Location_Id_4',
        ),
        migrations.AddField(
            model_name='foodremainingtimes',
            name='latitude',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodremainingtimes',
            name='longitude',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodremainingtimes',
            name='Food_Amount_gr',
            field=models.FloatField(),
        ),
    ]
