# Generated by Django 3.1.2 on 2020-10-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlAPI', '0004_auto_20201014_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodremainingtimes',
            old_name='latitude',
            new_name='Latitude',
        ),
        migrations.RenameField(
            model_name='foodremainingtimes',
            old_name='longitude',
            new_name='Longitude',
        ),
        migrations.AddField(
            model_name='foodremainingtimes',
            name='Prediction',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
