# Generated by Django 3.1.2 on 2020-10-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlAPI', '0006_emergency'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
