# Generated by Django 3.1.2 on 2020-10-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlAPI', '0007_emergency_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
