# Generated by Django 3.1.2 on 2020-10-18 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlAPI', '0008_auto_20201016_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsFoodFinished', models.IntegerField(blank=True, null=True)),
                ('Location_Id', models.IntegerField(blank=True, null=True)),
                ('Longitude', models.FloatField(blank=True, null=True)),
                ('Latitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
