# Generated by Django 3.1.2 on 2020-10-20 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlAPI', '0009_foodstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodOrNot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageBowl', models.CharField(blank=True, max_length=1000, null=True)),
                ('IsFood', models.IntegerField(blank=True, null=True)),
                ('Resolved', models.IntegerField(blank=True, null=True)),
                ('Location_Id', models.IntegerField(blank=True, null=True)),
                ('Longitude', models.FloatField(blank=True, null=True)),
                ('Latitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
